name: Link PR to Notion (Reusable)
on:
  workflow_call:
    inputs:
      pr_body:
        type: string
        required: true
      pr_title:
        type: string
        required: true
      pr_url:
        type: string
        required: true
      pr_number:
        type: string
        required: true
      pr_author:
        type: string
        required: false
        default: ""
      repository_name:
        type: string
        required: false
        default: ""
    secrets:
      NOTION_TOKEN:
        required: true
      NOTION_DATABASE_ID:
        required: true

jobs:
  link-notion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: replaceaidnet/.github
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install @notionhq/client@latest
      - name: Link PR to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          REPOSITORY_NAME: ${{ inputs.repository_name }}
          PR_BODY: ${{ inputs.pr_body }}
          PR_TITLE: ${{ inputs.pr_title }}
          PR_URL: ${{ inputs.pr_url }}
          PR_NUMBER: ${{ inputs.pr_number }}
          PR_AUTHOR: ${{ inputs.pr_author }}
        run: node .github/scripts/link-notion.js
